name: Build and push container image tagged with branch name
on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
    - name: Build and push Docker image to GitHub Package Registry
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
	name: ${{ github.repository }}
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: ghcr.io
